### ISSUE TITLE
Fails to build with --build-tests flag

### ISSUE THREAD

**Issue by ghost** [intel/ros2_message_filters#5]
If I try to build by running 

> ament build --build-tests ros2_message_filters

 I get a number of compile errors in "approximate_time.h" and "test_approximate_time_policy.cpp". This is preventing building with colcon because colcon builds tests by default.

**Comment by crdelsey** [comment]
I was able to workaround the problem by commenting out the approximate_time_policy test

> #ament_add_gtest(${PROJECT_NAME}-test_approximate_time_policy test/test_approximate_time_policy.cpp)

That's obviously not a permanent fix, but I'm not sure if that test is still relevant or exactly what it should do.

**Comment by gaoethan** [comment]
@crdelsey what ros2 branch did you build with the ros2_message_filters ?

**Comment by gaoethan** [comment]
It seems that the PR #6 relates to the fix to this issue, I built with latest ROS2 `master `branch with
`ament build --build-tests --symlink-install `
there is no building waring and error, so please share more details for your case, thanks ! 😄
